import { Driver, Race } from "./types";
import { f1People } from "./f1People";
import { wrcPeople } from "./wrcPeople";

const localDrivers: Driver[] = [
  {
    id: "sesks",
    name: "Mārtiņš Sesks",
    discipline: "Rally",
    achievements: [
      "Starptautisku ralliju starti (piemērs)",
      "Podiumi reģionālajās sacensībās (piemērs)",
    ],
    active: true,
  },
  {
    id: "ozols",
    name: "Markuss Ozols",
    discipline: "Drift",
    achievements: ["Latvijas Drift kausa posmu uzvaras (piemērs)"],
    active: true,
  },
  {
    id: "berzins",
    name: "Jānis Bērziņš",
    discipline: "Circuit",
    achievements: ["Sezonas TOP-3 (piemērs)"],
    active: true,
  },
];

export const races: Race[] = [
  // LATVIA
  {
    id: "riga-drift-open",
    title: "Riga Drift Open",
    startDate: "2026-04-12",
    country: "Latvia",
    city: "Riga",
    venue: "Biķernieku trase",
    region: "Latvia",
    series: "Drift",
    latviaInvolved: true,
    latvianDrivers: ["ozols"],
    links: { official: "https://example.com" },
    description: "Drifta sacensības Rīgā ar Baltijas braucējiem.",
  },

  {
    id: "washcar-riga-summer-race-2026",
    title: "WashCar Riga Summer Race 2026",
    startDate: "2026-05-02",
    endDate: "2026-05-03",
    country: "Latvia",
    city: "Riga",
    venue: "Bikernieki Track",
    location: "Riga, Latvia",
    region: "Latvia",
    series: "Circuit",
    latviaInvolved: true,
    latvianDrivers: ["berzins"],
    links: {
      official: "https://www.bilesuserviss.lv/lat/biletes/sports/washcar-riga-summer-race-2026-495890/",
    },
    description:
      "Baltic circuit racing weekend at Bikernieki with sprint classes and regional touring car action.",
  },
  {
    id: "euro-rx-of-latvia-2026",
    title: "Euro RX of Latvia 2026",
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    country: "Latvia",
    city: "Riga",
    venue: "Bikernieki Track",
    location: "Riga, Latvia",
    region: "Latvia",
    series: "Other",
    latviaInvolved: true,
    latvianDrivers: [],
    links: {
      official:
        "https://www.bilesuserviss.lv/lat/biletes/sports/fia-eiropas-rallijkrosa-cempionata-1-posms-euro-rx-of-latvia-495801/",
    },
    description:
      "FIA European Rallycross Championship opener in Riga at the Bikernieki rallycross circuit.",
  },
  {
    id: "drift-grand-opening-2026",
    title: "Drift Grand Opening 2026",
    startDate: "2026-05-16",
    endDate: "2026-05-17",
    country: "Latvia",
    city: "Riga",
    venue: "Bikernieki Track",
    location: "Riga, Latvia",
    region: "Latvia",
    series: "Drift",
    latviaInvolved: true,
    latvianDrivers: ["ozols"],
    links: {
      official: "https://www.bilesuserviss.lv/rus/bileti/sports/drift-grand-opening-2026-494522/",
    },
    description:
      "Baltic drift season opener with Street, PRO2 and PRO competition classes at Bikernieki.",
  },
  {
    id: "drift-masters-riga-2026",
    title: "Drift Masters Riga 2026",
    startDate: "2026-07-24",
    endDate: "2026-07-25",
    country: "Latvia",
    city: "Riga",
    venue: "Bikernieki Track",
    location: "Riga, Latvia",
    region: "Latvia",
    series: "Drift",
    latviaInvolved: true,
    latvianDrivers: ["ozols"],
    links: {
      official: "https://www.bilesuserviss.lv/eng/tickets/drift-masters-riga-2026-101717/",
    },
    description:
      "International Drift Masters round in Riga, one of the signature Bikernieki drift weekends of the year.",
  },

  // BALTICS
  {
    id: "palanga-1006",
    title: "Palanga 1006 km",
    startDate: "2026-07-16",
    country: "Lithuania",
    city: "Palanga",
    location: "Palanga, Lithuania",
    region: "Baltics",
    series: "Circuit",
    latviaInvolved: true,
    latvianDrivers: ["berzins"],
    links: { official: "https://www.racing.lt/en/events/1006-km-race" },
    description: "Baltic endurance racing highlight on the Lithuanian seaside with strong regional interest.",
  },
  {
    id: "rally-estonia",
    title: "WRC Delfi Rally Estonia 2026",
    startDate: "2026-07-16",
    endDate: "2026-07-19",
    country: "Estonia",
    city: "Tartu",
    location: "Tartu, Estonia",
    region: "Baltics",
    series: "Rally",
    latviaInvolved: true,
    latvianDrivers: ["sesks"],
    links: { official: "https://rallyestonia.ee/pealtvaatajale/uldinfo/" },
    description:
      "Official WRC round in South Estonia with fast gravel roads, Tartu service park and strong Baltic fan support.",
  },
  {
    id: "stateta-bro-pro-bro-grand-prix-riga-2026",
    title: "Stateta BRO / PRO BRO Grand Prix Riga",
    startDate: "2026-06-04",
    endDate: "2026-06-06",
    country: "Latvia",
    city: "Riga",
    venue: "Bikernieki Track",
    location: "Riga, Latvia",
    region: "Latvia",
    series: "Circuit",
    latviaInvolved: true,
    latvianDrivers: ["berzins"],
    links: { official: "https://batcc.eu/2025/12/stateta-bro-pro-bro-grand-prix-riga/" },
    description:
      "Major Baltic circuit racing weekend in Riga with touring, GT and endurance support categories.",
  },
  {
    id: "kaunas-grand-prix-2026",
    title: "Kaunas Grand Prix 2026",
    startDate: "2026-07-03",
    endDate: "2026-07-04",
    country: "Lithuania",
    city: "Kaunas",
    venue: "Nemuno Ziedas",
    location: "Kaunas, Lithuania",
    region: "Baltics",
    series: "Circuit",
    latviaInvolved: true,
    latvianDrivers: ["berzins"],
    links: { official: "https://www.balticracingseries.eu/calendar" },
    description:
      "Baltic circuit racing championship round at Nemuno Ziedas with sprint and endurance racing.",
  },
  {
    id: "parnu-summer-race-2026",
    title: "Parnu Summer Race 2026",
    startDate: "2026-08-27",
    endDate: "2026-08-30",
    country: "Estonia",
    city: "Parnu",
    venue: "Porsche Ring",
    location: "Parnu, Estonia",
    region: "Baltics",
    series: "Circuit",
    latviaInvolved: true,
    latvianDrivers: ["berzins"],
    links: { official: "https://www.balticracingseries.eu/calendar" },
    description:
      "Late-summer Baltic racing festival in Parnu with touring, time attack and endurance action.",
  },
  {
    id: "fia-karting-euro-la-conca-2026",
    title: "FIA Karting European Championship Round 1",
    startDate: "2026-04-09",
    endDate: "2026-04-12",
    country: "Italy",
    city: "Muro Leccese",
    venue: "World Circuit La Conca",
    location: "Muro Leccese, Italy",
    region: "World",
    series: "Karting",
    latviaInvolved: false,
    latvianDrivers: [],
    links: { official: "https://www.kartcom.com/en/news/2025/10/20/2026-fia-karting-calendar-approved-by-the-world-motor-sport-council/" },
    description:
      "Opening round of the 2026 FIA Karting European Championship for OK and OK-Junior classes.",
  },
  {
    id: "fia-karting-euro-genk-2026",
    title: "FIA Karting European Championship KZ/KZ2 Round 1",
    startDate: "2026-05-21",
    endDate: "2026-05-24",
    country: "Belgium",
    city: "Genk",
    venue: "Karting Genk",
    location: "Genk, Belgium",
    region: "World",
    series: "Karting",
    latviaInvolved: false,
    latvianDrivers: [],
    links: { official: "https://www.kartcom.com/en/news/2025/10/20/2026-fia-karting-calendar-approved-by-the-world-motor-sport-council/" },
    description:
      "European championship weekend for KZ and KZ2 categories, plus FIA Karting Academy support races.",
  },
  {
    id: "fia-karting-world-le-mans-2026",
    title: "FIA Karting World Championship KZ 2026",
    startDate: "2026-09-17",
    endDate: "2026-09-20",
    country: "France",
    city: "Le Mans",
    venue: "Le Mans Karting International",
    location: "Le Mans, France",
    region: "World",
    series: "Karting",
    latviaInvolved: false,
    latvianDrivers: [],
    links: { official: "https://www.kartcom.com/en/news/2025/10/20/2026-fia-karting-calendar-approved-by-the-world-motor-sport-council/" },
    description:
      "FIA Karting World Championship weekend for KZ, KZ2 World Cup and KZ2 Masters international classes.",
  },

  // WORLD (popular)
  {
    id: "f1-british-gp",
    title: "Formula 1 British GP",
    startDate: "2026-07-28",
    country: "United Kingdom",
    city: "Silverstone",
    region: "World",
    series: "F1",
    latviaInvolved: false,
    latvianDrivers: [],
    links: { official: "https://example.com", stream: "https://example.com" },
  },
  {
    id: "wrc-finland",
    title: "WRC Rally Finland",
    startDate: "2026-08-01",
    country: "Finland",
    city: "Jyväskylä",
    region: "World",
    series: "WRC",
    latviaInvolved: true,
    latvianDrivers: ["sesks"],
    links: { official: "https://example.com" },
  },
];

export const drivers: Driver[] = [...localDrivers, ...f1People, ...wrcPeople];
