import { Driver } from "./types";

export const f1People: Driver[] = [
  {
    id: "lando-norris",
    name: "Lando Norris",
    discipline: "Formula 1",
    role: "Driver",
    team: "McLaren",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["2025 F1 World Champion", "McLaren race winner"],
    bio: "McLaren's headline driver entering 2026 as the reigning world champion.",
    active: true,
  },
  {
    id: "oscar-piastri",
    name: "Oscar Piastri",
    discipline: "Formula 1",
    role: "Driver",
    team: "McLaren",
    nationality: "Australia",
    series: "F1",
    achievements: ["Grand Prix winner", "Part of McLaren's title-era lineup"],
    bio: "One of the sharpest young drivers on the grid and a constant threat over a full weekend.",
    active: true,
  },
  {
    id: "george-russell",
    name: "George Russell",
    discipline: "Formula 1",
    role: "Driver",
    team: "Mercedes",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Grand Prix winner", "Mercedes team leader"],
    bio: "Mercedes' lead driver, known for qualifying pace and strong race management.",
    active: true,
  },
  {
    id: "kimi-antonelli",
    name: "Kimi Antonelli",
    discipline: "Formula 1",
    role: "Driver",
    team: "Mercedes",
    nationality: "Italy",
    series: "F1",
    achievements: ["Mercedes junior graduate", "One of the youngest talents on the grid"],
    bio: "A high-upside Mercedes prospect learning quickly at the top level.",
    active: true,
  },
  {
    id: "max-verstappen",
    name: "Max Verstappen",
    discipline: "Formula 1",
    role: "Driver",
    team: "Red Bull Racing",
    nationality: "Netherlands",
    series: "F1",
    achievements: ["Multiple-time World Champion", "One of the benchmark drivers of the era"],
    bio: "Still one of the defining reference points for outright speed and racecraft.",
    active: true,
  },
  {
    id: "isack-hadjar",
    name: "Isack Hadjar",
    discipline: "Formula 1",
    role: "Driver",
    team: "Red Bull Racing",
    nationality: "France",
    series: "F1",
    achievements: ["Red Bull junior graduate", "Fast-rising F1 rookie talent"],
    bio: "A high-pressure Red Bull seat puts Hadjar in one of the sport's most demanding environments.",
    active: true,
  },
  {
    id: "charles-leclerc",
    name: "Charles Leclerc",
    discipline: "Formula 1",
    role: "Driver",
    team: "Ferrari",
    nationality: "Monaco",
    series: "F1",
    achievements: ["Multiple Grand Prix winner", "Ferrari front-line driver"],
    bio: "Leclerc remains central to Ferrari's hopes thanks to elite single-lap speed and proven race pace.",
    active: true,
  },
  {
    id: "lewis-hamilton",
    name: "Lewis Hamilton",
    discipline: "Formula 1",
    role: "Driver",
    team: "Ferrari",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Seven-time World Champion", "One of F1's most successful drivers"],
    bio: "Hamilton's Ferrari chapter makes every major weekend feel bigger and more historic.",
    active: true,
  },
  {
    id: "carlos-sainz",
    name: "Carlos Sainz",
    discipline: "Formula 1",
    role: "Driver",
    team: "Williams",
    nationality: "Spain",
    series: "F1",
    achievements: ["Grand Prix winner", "Experienced race-weekend operator"],
    bio: "A proven all-rounder whose technical feedback and consistency lift any team around him.",
    active: true,
  },
  {
    id: "alexander-albon",
    name: "Alexander Albon",
    discipline: "Formula 1",
    role: "Driver",
    team: "Williams",
    nationality: "Thailand",
    series: "F1",
    achievements: ["Grand Prix podium finisher", "Williams leader through its rebuild"],
    bio: "Albon is known for extracting strong race results even when outright pace is limited.",
    active: true,
  },
  {
    id: "fernando-alonso",
    name: "Fernando Alonso",
    discipline: "Formula 1",
    role: "Driver",
    team: "Aston Martin",
    nationality: "Spain",
    series: "F1",
    achievements: ["Two-time World Champion", "One of the grid's most experienced racers"],
    bio: "Alonso brings elite racecraft, relentless competitiveness and deep technical feel.",
    active: true,
  },
  {
    id: "lance-stroll",
    name: "Lance Stroll",
    discipline: "Formula 1",
    role: "Driver",
    team: "Aston Martin",
    nationality: "Canada",
    series: "F1",
    achievements: ["Grand Prix podium finisher", "Long-term Aston Martin driver"],
    bio: "Stroll offers continuity inside a team that is still building toward the front.",
    active: true,
  },
  {
    id: "nico-hulkenberg",
    name: "Nico Hulkenberg",
    discipline: "Formula 1",
    role: "Driver",
    team: "Audi",
    nationality: "Germany",
    series: "F1",
    achievements: ["Veteran F1 points scorer", "Key part of Audi's first works-era lineup"],
    bio: "Hulkenberg gives Audi a reliable, experienced reference as the brand establishes itself.",
    active: true,
  },
  {
    id: "gabriel-bortoleto",
    name: "Gabriel Bortoleto",
    discipline: "Formula 1",
    role: "Driver",
    team: "Audi",
    nationality: "Brazil",
    series: "F1",
    achievements: ["Audi young prospect", "Rising international junior talent"],
    bio: "Bortoleto represents Audi's longer-term project and development upside.",
    active: true,
  },
  {
    id: "pierre-gasly",
    name: "Pierre Gasly",
    discipline: "Formula 1",
    role: "Driver",
    team: "Alpine",
    nationality: "France",
    series: "F1",
    achievements: ["Grand Prix winner", "Experienced Alpine team leader"],
    bio: "Gasly combines proven top-level pace with the experience to lead a midfield program.",
    active: true,
  },
  {
    id: "franco-colapinto",
    name: "Franco Colapinto",
    discipline: "Formula 1",
    role: "Driver",
    team: "Alpine",
    nationality: "Argentina",
    series: "F1",
    achievements: ["Young F1 talent", "Brings fresh attention and upside to Alpine"],
    bio: "Colapinto adds new energy and a big fanbase to Alpine's 2026 lineup.",
    active: true,
  },
  {
    id: "esteban-ocon",
    name: "Esteban Ocon",
    discipline: "Formula 1",
    role: "Driver",
    team: "Haas F1 Team",
    nationality: "France",
    series: "F1",
    achievements: ["Grand Prix winner", "Strong reputation for race-day execution"],
    bio: "Ocon gives Haas a proven benchmark and a strong record in tightly contested weekends.",
    active: true,
  },
  {
    id: "oliver-bearman",
    name: "Oliver Bearman",
    discipline: "Formula 1",
    role: "Driver",
    team: "Haas F1 Team",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Ferrari academy graduate", "One of the grid's young breakout names"],
    bio: "Bearman remains one of the most watched young talents in the paddock.",
    active: true,
  },
  {
    id: "liam-lawson",
    name: "Liam Lawson",
    discipline: "Formula 1",
    role: "Driver",
    team: "Racing Bulls",
    nationality: "New Zealand",
    series: "F1",
    achievements: ["Red Bull family driver", "Known for adaptability in changing situations"],
    bio: "Lawson's flexibility and aggression make him an interesting watch on mixed weekends.",
    active: true,
  },
  {
    id: "arvid-lindblad",
    name: "Arvid Lindblad",
    discipline: "Formula 1",
    role: "Driver",
    team: "Racing Bulls",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["One of the youngest F1 arrivals", "Highly rated Red Bull junior"],
    bio: "Lindblad brings youth, speed and long-term star potential into the F1 field.",
    active: true,
  },
  {
    id: "sergio-perez",
    name: "Sergio Perez",
    discipline: "Formula 1",
    role: "Driver",
    team: "Cadillac",
    nationality: "Mexico",
    series: "F1",
    achievements: ["Multiple Grand Prix winner", "Experienced hand for an expansion team"],
    bio: "Perez gives Cadillac race-winning experience as the new team enters Formula 1.",
    active: true,
  },
  {
    id: "valtteri-bottas",
    name: "Valtteri Bottas",
    discipline: "Formula 1",
    role: "Driver",
    team: "Cadillac",
    nationality: "Finland",
    series: "F1",
    achievements: ["Grand Prix winner", "Experienced development driver"],
    bio: "Bottas adds technical clarity and calm execution to Cadillac's first-season effort.",
    active: true,
  },
  {
    id: "andrea-stella",
    name: "Andrea Stella",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "McLaren",
    nationality: "Italy",
    series: "F1",
    achievements: ["McLaren Team Principal", "Led McLaren through its title resurgence"],
    bio: "Stella is one of the key architects behind McLaren's modern rise back to the front.",
    active: true,
  },
  {
    id: "toto-wolff",
    name: "Toto Wolff",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Mercedes",
    nationality: "Austria",
    series: "F1",
    achievements: ["Mercedes Team Principal", "Central figure in one of F1's great dynasties"],
    bio: "Wolff blends management, strategy and driver development at championship level.",
    active: true,
  },
  {
    id: "laurent-mekies",
    name: "Laurent Mekies",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Red Bull Racing",
    nationality: "France",
    series: "F1",
    achievements: ["Red Bull Team Principal", "Former Racing Bulls and Ferrari senior figure"],
    bio: "Mekies took over one of the most intense leadership roles on the grid heading into 2026.",
    active: true,
  },
  {
    id: "fred-vasseur",
    name: "Fred Vasseur",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Ferrari",
    nationality: "France",
    series: "F1",
    achievements: ["Ferrari Team Principal", "Longtime leader across junior categories and F1 teams"],
    bio: "Vasseur oversees one of the sport's biggest pressure environments at Ferrari.",
    active: true,
  },
  {
    id: "james-vowles",
    name: "James Vowles",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Williams",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Williams Team Principal", "Former Mercedes strategy leader"],
    bio: "Vowles is driving Williams' long-term rebuild with a strong technical and strategic background.",
    active: true,
  },
  {
    id: "alan-permane",
    name: "Alan Permane",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Racing Bulls",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Racing Bulls Team Principal", "Veteran engineer with decades in F1"],
    bio: "Permane brings deep paddock experience to one of F1's development-focused teams.",
    active: true,
  },
  {
    id: "adrian-newey",
    name: "Adrian Newey",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Aston Martin",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Aston Martin Team Principal", "One of F1's most famous technical minds"],
    bio: "Newey's presence makes Aston Martin one of the most watched projects in the paddock.",
    active: true,
  },
  {
    id: "ayao-komatsu",
    name: "Ayao Komatsu",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Haas F1 Team",
    nationality: "Japan",
    series: "F1",
    achievements: ["Haas Team Principal", "Rose through engineering into team leadership"],
    bio: "Komatsu is tasked with turning Haas into a sharper, more consistently competitive operation.",
    active: true,
  },
  {
    id: "jonathan-wheatley",
    name: "Jonathan Wheatley",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Audi",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Audi Team Principal", "Former Red Bull Sporting Director"],
    bio: "Wheatley leads Audi into its new works-era identity in Formula 1.",
    active: true,
  },
  {
    id: "steve-nielsen",
    name: "Steve Nielsen",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Alpine",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Alpine leadership figure", "Oversees Alpine day-to-day operations in 2026"],
    bio: "Nielsen's operational experience makes him a key figure inside Alpine's reset.",
    active: true,
  },
  {
    id: "graeme-lowdon",
    name: "Graeme Lowdon",
    discipline: "Formula 1 leadership",
    role: "Team Principal",
    team: "Cadillac",
    nationality: "United Kingdom",
    series: "F1",
    achievements: ["Cadillac Team Principal", "Experienced in building new F1 projects"],
    bio: "Lowdon leads the challenge of launching Cadillac's first Formula 1 campaign.",
    active: true,
  },
];
