import { Race } from "./types";

type WorldRaceInput = {
  id: string;
  title: string;
  startDate: string;
  endDate?: string;
  country: string;
  city: string;
  venue: string;
  series: Race["series"];
  officialUrl: string;
  sourceLabel: string;
  description: string;
  featured?: boolean;
  popularityScore?: number;
  streamUrl?: string;
  ticketsUrl?: string;
};

function worldRace(input: WorldRaceInput): Race {
  return {
    id: input.id,
    title: input.title,
    startDate: input.startDate,
    endDate: input.endDate,
    country: input.country,
    city: input.city,
    venue: input.venue,
    location: `${input.venue}, ${input.city}, ${input.country}`,
    region: "World",
    series: input.series,
    latviaInvolved: false,
    latvianDrivers: [],
    links: {
      official: input.officialUrl,
      stream: input.streamUrl,
      tickets: input.ticketsUrl,
    },
    description: input.description,
    source: {
      type: "manual",
      label: input.sourceLabel,
      url: input.officialUrl,
    },
    featured: input.featured,
    popularityScore: input.popularityScore,
  };
}

const WEC_SOURCE_URL = "https://www.fiawec.com/en/page/official-programme";
const FORMULA_E_SOURCE_URL = "https://www.fiaformulae.com/en/calendar/2025-26";
const MOTOGP_SOURCE_URL = "https://www.motogp.com/en/calendar/2026";
const NASCAR_SOURCE_URL =
  "https://www.nascar.com/news-media/2025/08/20/nascar-releases-2026-schedule-adding-chicagoland-and-shifting-all-star-to-dover/";

export const worldCalendarRaces: Race[] = [
  worldRace({
    id: "wec-2026-04-17-6-hours-of-imola",
    title: "WEC 6 Hours of Imola 2026",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
    country: "Italy",
    city: "Imola",
    venue: "Autodromo Internazionale Enzo e Dino Ferrari",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "The 2026 FIA WEC season opener after the Qatar round was moved later in the year.",
    featured: true,
    popularityScore: 86,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-05-07-6-hours-of-spa",
    title: "WEC TotalEnergies 6 Hours of Spa-Francorchamps 2026",
    startDate: "2026-05-07",
    endDate: "2026-05-09",
    country: "Belgium",
    city: "Stavelot",
    venue: "Circuit de Spa-Francorchamps",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "A classic FIA WEC endurance weekend at Spa-Francorchamps before Le Mans.",
    featured: true,
    popularityScore: 88,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-06-10-24-hours-of-le-mans",
    title: "24 Hours of Le Mans 2026",
    startDate: "2026-06-10",
    endDate: "2026-06-14",
    country: "France",
    city: "Le Mans",
    venue: "Circuit de la Sarthe",
    series: "WEC",
    officialUrl: "https://www.fia.com/championship/events/world-endurance-championship/season-2026/24-hours-le-mans",
    sourceLabel: "FIA WEC schedule",
    description: "The headline endurance race of the year and a must-have world event for a serious motorsport calendar.",
    featured: true,
    popularityScore: 100,
    streamUrl: "https://www.fiawec.tv/",
    ticketsUrl: "https://www.24h-lemans.com/en/tickets",
  }),
  worldRace({
    id: "wec-2026-07-10-6-hours-of-sao-paulo",
    title: "WEC Rolex 6 Hours of Sao Paulo 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    country: "Brazil",
    city: "Sao Paulo",
    venue: "Interlagos",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "FIA WEC's South American round at Interlagos.",
    popularityScore: 84,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-09-04-lone-star-le-mans",
    title: "WEC Lone Star Le Mans 2026",
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    country: "United States",
    city: "Austin",
    venue: "Circuit of The Americas",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "The FIA WEC North American round at Circuit of The Americas.",
    featured: true,
    popularityScore: 86,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-09-25-6-hours-of-fuji",
    title: "WEC 6 Hours of Fuji 2026",
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    country: "Japan",
    city: "Oyama",
    venue: "Fuji Speedway",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "The Japanese FIA WEC round at Fuji Speedway.",
    popularityScore: 84,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-10-22-qatar-1812km",
    title: "WEC Qatar 1812km 2026",
    startDate: "2026-10-22",
    endDate: "2026-10-24",
    country: "Qatar",
    city: "Lusail",
    venue: "Lusail International Circuit",
    series: "WEC",
    officialUrl: "https://www.fiawec.com/en/news/dates-confirmed-for-rescheduled-qatar-1812km-and-fia-wec-prologue/13118",
    sourceLabel: "Official FIA WEC rescheduled date",
    description: "The Qatar 1812km was rescheduled from March to 22-24 October 2026.",
    featured: true,
    popularityScore: 87,
    streamUrl: "https://www.fiawec.tv/",
  }),
  worldRace({
    id: "wec-2026-11-05-8-hours-of-bahrain",
    title: "WEC Bapco Energies 8 Hours of Bahrain 2026",
    startDate: "2026-11-05",
    endDate: "2026-11-07",
    country: "Bahrain",
    city: "Sakhir",
    venue: "Bahrain International Circuit",
    series: "WEC",
    officialUrl: WEC_SOURCE_URL,
    sourceLabel: "Official FIA WEC programme",
    description: "The FIA WEC season finale in Bahrain.",
    featured: true,
    popularityScore: 86,
    streamUrl: "https://www.fiawec.tv/",
  }),

  worldRace({
    id: "formula-e-2026-05-02-berlin-eprix",
    title: "Formula E Berlin E-Prix Double-Header 2026",
    startDate: "2026-05-02",
    endDate: "2026-05-03",
    country: "Germany",
    city: "Berlin",
    venue: "Tempelhof Airport Street Circuit",
    series: "Formula E",
    officialUrl: "https://www.fiaformulae.com/en/events/2025-26/berlin",
    sourceLabel: "Official Formula E calendar",
    description: "A two-race Formula E weekend at Tempelhof, with rounds 7 and 8 on 2-3 May.",
    featured: true,
    popularityScore: 86,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),
  worldRace({
    id: "formula-e-2026-05-16-monaco-eprix",
    title: "Formula E Monaco E-Prix Double-Header 2026",
    startDate: "2026-05-16",
    endDate: "2026-05-17",
    country: "Monaco",
    city: "Monte Carlo",
    venue: "Circuit de Monaco",
    series: "Formula E",
    officialUrl: "https://www.fiaformulae.com/en/events/2025-26/monaco",
    sourceLabel: "Official Formula E calendar",
    description: "A Monaco Formula E double-header with rounds 9 and 10 on the streets of Monte Carlo.",
    featured: true,
    popularityScore: 84,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),
  worldRace({
    id: "formula-e-2026-06-20-sanya-eprix",
    title: "Formula E Sanya E-Prix 2026",
    startDate: "2026-06-20",
    country: "China",
    city: "Sanya",
    venue: "Haitang Bay Circuit",
    series: "Formula E",
    officialUrl: FORMULA_E_SOURCE_URL,
    sourceLabel: "Official Formula E calendar",
    description: "Formula E's Sanya round in China.",
    popularityScore: 76,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),
  worldRace({
    id: "formula-e-2026-07-04-shanghai-eprix",
    title: "Formula E Shanghai E-Prix Double-Header 2026",
    startDate: "2026-07-04",
    endDate: "2026-07-05",
    country: "China",
    city: "Shanghai",
    venue: "Shanghai International Circuit",
    series: "Formula E",
    officialUrl: FORMULA_E_SOURCE_URL,
    sourceLabel: "Official Formula E calendar",
    description: "A two-race Formula E weekend at Shanghai International Circuit.",
    popularityScore: 78,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),
  worldRace({
    id: "formula-e-2026-07-25-tokyo-eprix",
    title: "Formula E Tokyo E-Prix Double-Header 2026",
    startDate: "2026-07-25",
    endDate: "2026-07-26",
    country: "Japan",
    city: "Tokyo",
    venue: "Tokyo Street Circuit",
    series: "Formula E",
    officialUrl: FORMULA_E_SOURCE_URL,
    sourceLabel: "Official Formula E calendar",
    description: "A Tokyo Formula E double-header in late July.",
    featured: true,
    popularityScore: 82,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),
  worldRace({
    id: "formula-e-2026-08-15-london-eprix",
    title: "Formula E London E-Prix Double-Header 2026",
    startDate: "2026-08-15",
    endDate: "2026-08-16",
    country: "United Kingdom",
    city: "London",
    venue: "ExCeL London",
    series: "Formula E",
    officialUrl: FORMULA_E_SOURCE_URL,
    sourceLabel: "Official Formula E calendar",
    description: "Formula E's London season finale double-header.",
    featured: true,
    popularityScore: 84,
    streamUrl: "https://www.fiaformulae.com/en/ways-to-watch",
  }),

  worldRace({
    id: "motogp-2026-04-24-spanish-grand-prix",
    title: "MotoGP Spanish Grand Prix 2026",
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    country: "Spain",
    city: "Jerez",
    venue: "Circuito de Jerez-Angel Nieto",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Spanish Grand Prix weekend at Jerez.",
    featured: true,
    popularityScore: 82,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-05-08-french-grand-prix",
    title: "MotoGP French Grand Prix 2026",
    startDate: "2026-05-08",
    endDate: "2026-05-10",
    country: "France",
    city: "Le Mans",
    venue: "Bugatti Circuit",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's French Grand Prix weekend at Le Mans.",
    popularityScore: 80,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-05-15-catalan-grand-prix",
    title: "MotoGP Catalan Grand Prix 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    country: "Spain",
    city: "Barcelona",
    venue: "Circuit de Barcelona-Catalunya",
    series: "MotoGP",
    officialUrl: "https://www.motogp.com/en/calendar/2026/event/catalunya/200bf59d-3db2-4e17-a903-4be204fa3496",
    sourceLabel: "Official MotoGP calendar",
    description: "A popular MotoGP weekend at Barcelona-Catalunya.",
    featured: true,
    popularityScore: 83,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-05-29-italian-grand-prix",
    title: "MotoGP Italian Grand Prix 2026",
    startDate: "2026-05-29",
    endDate: "2026-05-31",
    country: "Italy",
    city: "Mugello",
    venue: "Mugello Circuit",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Italian Grand Prix weekend at Mugello.",
    popularityScore: 82,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-06-05-hungarian-grand-prix",
    title: "MotoGP Hungarian Grand Prix 2026",
    startDate: "2026-06-05",
    endDate: "2026-06-07",
    country: "Hungary",
    city: "Balatonfokajar",
    venue: "Balaton Park Circuit",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Hungarian Grand Prix weekend at Balaton Park.",
    popularityScore: 76,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-06-19-czech-grand-prix",
    title: "MotoGP Czech Grand Prix 2026",
    startDate: "2026-06-19",
    endDate: "2026-06-21",
    country: "Czechia",
    city: "Brno",
    venue: "Automotodrom Brno",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Czech Grand Prix weekend at Brno.",
    popularityScore: 77,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-06-26-dutch-grand-prix",
    title: "MotoGP Dutch Grand Prix 2026",
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    country: "Netherlands",
    city: "Assen",
    venue: "TT Circuit Assen",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Dutch TT weekend at Assen.",
    popularityScore: 82,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-07-10-german-grand-prix",
    title: "MotoGP German Grand Prix 2026",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    country: "Germany",
    city: "Hohenstein-Ernstthal",
    venue: "Sachsenring",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's German Grand Prix weekend at the Sachsenring.",
    popularityScore: 80,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-08-07-british-grand-prix",
    title: "MotoGP British Grand Prix 2026",
    startDate: "2026-08-07",
    endDate: "2026-08-09",
    country: "United Kingdom",
    city: "Silverstone",
    venue: "Silverstone Circuit",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's British Grand Prix weekend at Silverstone.",
    featured: true,
    popularityScore: 82,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-08-28-aragon-grand-prix",
    title: "MotoGP Aragon Grand Prix 2026",
    startDate: "2026-08-28",
    endDate: "2026-08-30",
    country: "Spain",
    city: "Alcaniz",
    venue: "MotorLand Aragon",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Aragon Grand Prix weekend at MotorLand.",
    popularityScore: 78,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-09-11-san-marino-grand-prix",
    title: "MotoGP San Marino Grand Prix 2026",
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    country: "San Marino",
    city: "Misano Adriatico",
    venue: "Misano World Circuit Marco Simoncelli",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's San Marino Grand Prix weekend at Misano.",
    popularityScore: 80,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-09-18-austrian-grand-prix",
    title: "MotoGP Austrian Grand Prix 2026",
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    country: "Austria",
    city: "Spielberg",
    venue: "Red Bull Ring",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Austrian Grand Prix weekend at the Red Bull Ring.",
    popularityScore: 80,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-10-02-japanese-grand-prix",
    title: "MotoGP Japanese Grand Prix 2026",
    startDate: "2026-10-02",
    endDate: "2026-10-04",
    country: "Japan",
    city: "Motegi",
    venue: "Mobility Resort Motegi",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Japanese Grand Prix weekend at Motegi.",
    popularityScore: 79,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-10-23-australian-grand-prix",
    title: "MotoGP Australian Grand Prix 2026",
    startDate: "2026-10-23",
    endDate: "2026-10-25",
    country: "Australia",
    city: "Phillip Island",
    venue: "Phillip Island Grand Prix Circuit",
    series: "MotoGP",
    officialUrl: "https://www.motogp.com/en/calendar/2026/event/australia/66961f05-2454-4455-9d65-f99c49d25b17",
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Australian Grand Prix weekend at Phillip Island.",
    featured: true,
    popularityScore: 83,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-10-30-malaysian-grand-prix",
    title: "MotoGP Malaysian Grand Prix 2026",
    startDate: "2026-10-30",
    endDate: "2026-11-01",
    country: "Malaysia",
    city: "Sepang",
    venue: "Sepang International Circuit",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's Malaysian Grand Prix weekend at Sepang.",
    popularityScore: 79,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-11-06-qatar-grand-prix",
    title: "MotoGP Qatar Grand Prix 2026",
    startDate: "2026-11-06",
    endDate: "2026-11-08",
    country: "Qatar",
    city: "Lusail",
    venue: "Lusail International Circuit",
    series: "MotoGP",
    officialUrl: "https://www.motogp.com/en/news/2025/04/07/motogp-konfirmasi-penundaan-gp-qatar-2026/1005668",
    sourceLabel: "Official MotoGP rescheduled date",
    description: "MotoGP moved the Qatar Grand Prix to 6-8 November 2026.",
    featured: true,
    popularityScore: 82,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-11-13-portuguese-grand-prix",
    title: "MotoGP Portuguese Grand Prix 2026",
    startDate: "2026-11-13",
    endDate: "2026-11-15",
    country: "Portugal",
    city: "Portimao",
    venue: "Autodromo Internacional do Algarve",
    series: "MotoGP",
    officialUrl: "https://motogppremier.motogp.com/po/2026-motogp-portugal",
    sourceLabel: "Official MotoGP ticket package schedule",
    description: "MotoGP's Portuguese Grand Prix weekend at Portimao.",
    popularityScore: 79,
    streamUrl: "https://www.motogp.com/",
  }),
  worldRace({
    id: "motogp-2026-11-27-valencian-grand-prix",
    title: "MotoGP Valencian Grand Prix 2026",
    startDate: "2026-11-27",
    endDate: "2026-11-29",
    country: "Spain",
    city: "Valencia",
    venue: "Circuit Ricardo Tormo",
    series: "MotoGP",
    officialUrl: MOTOGP_SOURCE_URL,
    sourceLabel: "Official MotoGP calendar",
    description: "MotoGP's rescheduled season finale in Valencia.",
    featured: true,
    popularityScore: 83,
    streamUrl: "https://www.motogp.com/",
  }),

  worldRace({
    id: "nascar-2026-04-26-talladega",
    title: "NASCAR Talladega Cup Race 2026",
    startDate: "2026-04-26",
    country: "United States",
    city: "Talladega",
    venue: "Talladega Superspeedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series spring race at Talladega Superspeedway.",
    featured: true,
    popularityScore: 82,
  }),
  worldRace({
    id: "nascar-2026-05-03-texas",
    title: "NASCAR Texas Cup Race 2026",
    startDate: "2026-05-03",
    country: "United States",
    city: "Fort Worth",
    venue: "Texas Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Texas Motor Speedway.",
    popularityScore: 76,
  }),
  worldRace({
    id: "nascar-2026-05-10-watkins-glen",
    title: "NASCAR Watkins Glen Cup Weekend 2026",
    startDate: "2026-05-10",
    country: "United States",
    city: "Watkins Glen",
    venue: "Watkins Glen International",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR road-course race at Watkins Glen International.",
    featured: true,
    popularityScore: 80,
  }),
  worldRace({
    id: "nascar-2026-05-17-all-star-dover",
    title: "NASCAR All-Star Race at Dover 2026",
    startDate: "2026-05-17",
    country: "United States",
    city: "Dover",
    venue: "Dover Motor Speedway",
    series: "NASCAR",
    officialUrl: "https://www.nascar.com/news-media/2026/02/25/format-for-2026-nascar-all-star-race-revealed/",
    sourceLabel: "Official NASCAR All-Star schedule",
    description: "The 2026 NASCAR All-Star Race at Dover Motor Speedway.",
    featured: true,
    popularityScore: 83,
  }),
  worldRace({
    id: "nascar-2026-05-24-coca-cola-600",
    title: "NASCAR Coca-Cola 600 2026",
    startDate: "2026-05-24",
    country: "United States",
    city: "Concord",
    venue: "Charlotte Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A crown-jewel NASCAR Cup race at Charlotte Motor Speedway.",
    featured: true,
    popularityScore: 86,
  }),
  worldRace({
    id: "nascar-2026-05-31-nashville",
    title: "NASCAR Nashville Cup Race 2026",
    startDate: "2026-05-31",
    country: "United States",
    city: "Lebanon",
    venue: "Nashville Superspeedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Nashville Superspeedway.",
    popularityScore: 75,
  }),
  worldRace({
    id: "nascar-2026-06-07-michigan",
    title: "NASCAR Michigan Cup Race 2026",
    startDate: "2026-06-07",
    country: "United States",
    city: "Brooklyn",
    venue: "Michigan International Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Michigan International Speedway.",
    popularityScore: 75,
  }),
  worldRace({
    id: "nascar-2026-06-14-pocono",
    title: "NASCAR Pocono Cup Race 2026",
    startDate: "2026-06-14",
    country: "United States",
    city: "Long Pond",
    venue: "Pocono Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Pocono Raceway.",
    popularityScore: 75,
  }),
  worldRace({
    id: "nascar-2026-06-21-san-diego",
    title: "NASCAR San Diego Street Race 2026",
    startDate: "2026-06-21",
    country: "United States",
    city: "San Diego",
    venue: "Naval Base Coronado",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup Series street-course event at Naval Base Coronado.",
    featured: true,
    popularityScore: 84,
  }),
  worldRace({
    id: "nascar-2026-06-28-sonoma",
    title: "NASCAR Sonoma Cup Race 2026",
    startDate: "2026-06-28",
    country: "United States",
    city: "Sonoma",
    venue: "Sonoma Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Sonoma Raceway.",
    featured: true,
    popularityScore: 80,
  }),
  worldRace({
    id: "nascar-2026-07-05-chicagoland",
    title: "NASCAR Chicagoland Cup Race 2026",
    startDate: "2026-07-05",
    country: "United States",
    city: "Joliet",
    venue: "Chicagoland Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series returns to Chicagoland Speedway.",
    featured: true,
    popularityScore: 82,
  }),
  worldRace({
    id: "nascar-2026-07-12-atlanta",
    title: "NASCAR Atlanta Cup Race 2026",
    startDate: "2026-07-12",
    country: "United States",
    city: "Hampton",
    venue: "EchoPark Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at EchoPark Speedway in Atlanta.",
    popularityScore: 76,
  }),
  worldRace({
    id: "nascar-2026-07-19-north-wilkesboro",
    title: "NASCAR North Wilkesboro Cup Race 2026",
    startDate: "2026-07-19",
    country: "United States",
    city: "North Wilkesboro",
    venue: "North Wilkesboro Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "North Wilkesboro hosts its first NASCAR Cup points race in decades.",
    featured: true,
    popularityScore: 84,
  }),
  worldRace({
    id: "nascar-2026-07-26-indianapolis",
    title: "NASCAR Indianapolis Cup Race 2026",
    startDate: "2026-07-26",
    country: "United States",
    city: "Speedway",
    venue: "Indianapolis Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Indianapolis Motor Speedway.",
    featured: true,
    popularityScore: 84,
  }),
  worldRace({
    id: "nascar-2026-08-09-iowa",
    title: "NASCAR Iowa Cup Race 2026",
    startDate: "2026-08-09",
    country: "United States",
    city: "Newton",
    venue: "Iowa Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Iowa Speedway.",
    popularityScore: 74,
  }),
  worldRace({
    id: "nascar-2026-08-15-richmond",
    title: "NASCAR Richmond Cup Race 2026",
    startDate: "2026-08-15",
    country: "United States",
    city: "Richmond",
    venue: "Richmond Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at Richmond Raceway.",
    popularityScore: 74,
  }),
  worldRace({
    id: "nascar-2026-08-23-new-hampshire",
    title: "NASCAR New Hampshire Cup Race 2026",
    startDate: "2026-08-23",
    country: "United States",
    city: "Loudon",
    venue: "New Hampshire Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup Series race at New Hampshire Motor Speedway.",
    popularityScore: 74,
  }),
  worldRace({
    id: "nascar-2026-08-29-daytona",
    title: "NASCAR Daytona Summer Race 2026",
    startDate: "2026-08-29",
    country: "United States",
    city: "Daytona Beach",
    venue: "Daytona International Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The late-summer NASCAR Cup race at Daytona International Speedway.",
    featured: true,
    popularityScore: 84,
  }),
  worldRace({
    id: "nascar-2026-09-06-darlington",
    title: "NASCAR Darlington Playoff Race 2026",
    startDate: "2026-09-06",
    country: "United States",
    city: "Darlington",
    venue: "Darlington Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The NASCAR Cup playoff opener at Darlington Raceway.",
    featured: true,
    popularityScore: 83,
  }),
  worldRace({
    id: "nascar-2026-09-13-gateway",
    title: "NASCAR Gateway Playoff Race 2026",
    startDate: "2026-09-13",
    country: "United States",
    city: "Madison",
    venue: "World Wide Technology Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at World Wide Technology Raceway.",
    popularityScore: 76,
  }),
  worldRace({
    id: "nascar-2026-09-19-bristol",
    title: "NASCAR Bristol Night Race 2026",
    startDate: "2026-09-19",
    country: "United States",
    city: "Bristol",
    venue: "Bristol Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race under the lights at Bristol.",
    featured: true,
    popularityScore: 84,
  }),
  worldRace({
    id: "nascar-2026-09-27-kansas",
    title: "NASCAR Kansas Playoff Race 2026",
    startDate: "2026-09-27",
    country: "United States",
    city: "Kansas City",
    venue: "Kansas Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at Kansas Speedway.",
    popularityScore: 76,
  }),
  worldRace({
    id: "nascar-2026-10-04-las-vegas",
    title: "NASCAR Las Vegas Playoff Race 2026",
    startDate: "2026-10-04",
    country: "United States",
    city: "Las Vegas",
    venue: "Las Vegas Motor Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at Las Vegas Motor Speedway.",
    popularityScore: 78,
  }),
  worldRace({
    id: "nascar-2026-10-11-charlotte-roval",
    title: "NASCAR Charlotte Roval Playoff Race 2026",
    startDate: "2026-10-11",
    country: "United States",
    city: "Concord",
    venue: "Charlotte Motor Speedway Roval",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff road-course race at the Charlotte Roval.",
    featured: true,
    popularityScore: 82,
  }),
  worldRace({
    id: "nascar-2026-10-18-phoenix",
    title: "NASCAR Phoenix Playoff Race 2026",
    startDate: "2026-10-18",
    country: "United States",
    city: "Avondale",
    venue: "Phoenix Raceway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at Phoenix Raceway.",
    popularityScore: 78,
  }),
  worldRace({
    id: "nascar-2026-10-25-talladega-playoff",
    title: "NASCAR Talladega Playoff Race 2026",
    startDate: "2026-10-25",
    country: "United States",
    city: "Talladega",
    venue: "Talladega Superspeedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at Talladega Superspeedway.",
    featured: true,
    popularityScore: 83,
  }),
  worldRace({
    id: "nascar-2026-11-01-martinsville",
    title: "NASCAR Martinsville Playoff Race 2026",
    startDate: "2026-11-01",
    country: "United States",
    city: "Martinsville",
    venue: "Martinsville Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "A NASCAR Cup playoff race at Martinsville Speedway.",
    popularityScore: 79,
  }),
  worldRace({
    id: "nascar-2026-11-08-homestead-championship",
    title: "NASCAR Championship at Homestead-Miami 2026",
    startDate: "2026-11-08",
    country: "United States",
    city: "Homestead",
    venue: "Homestead-Miami Speedway",
    series: "NASCAR",
    officialUrl: NASCAR_SOURCE_URL,
    sourceLabel: "Official NASCAR Cup schedule",
    description: "The 2026 NASCAR Cup Series championship finale at Homestead-Miami Speedway.",
    featured: true,
    popularityScore: 88,
  }),
];
