import { Race } from "./types";

export const wrcFallbackRaces: Race[] = [
  {
    id: "wrc-2026-01-22-wrc-rallye-monte-carlo",
    title: "WRC Rallye Monte-Carlo",
    startDate: "2026-01-22",
    country: "Monaco",
    city: "Monte-Carlo",
    location: "Monte-Carlo, Monaco",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/calendar?rb3TabId=upcoming" },
  },
  {
    id: "wrc-2026-02-12-wrc-rally-sweden",
    title: "WRC Rally Sweden",
    startDate: "2026-02-12",
    country: "Sweden",
    city: "Umea",
    location: "Umea, Sweden",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/calendar?rb3TabId=upcoming" },
  },
  {
    id: "wrc-2026-03-12-wrc-safari-rally-kenya-2026",
    title: "WRC Safari Rally Kenya 2026",
    startDate: "2026-03-12",
    country: "Kenya",
    city: "Kenya",
    location: "Kenya",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-safari-rally-kenya-2026" },
  },
  {
    id: "wrc-2026-04-10-wrc-croatia-rally-2026",
    title: "WRC Croatia Rally 2026",
    startDate: "2026-04-10",
    country: "Croatia",
    city: "Croatia",
    location: "Croatia",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-croatia-rally-2026" },
  },
  {
    id: "wrc-2026-04-23-wrc-rally-islas-canarias-2026",
    title: "WRC Rally Islas Canarias 2026",
    startDate: "2026-04-23",
    country: "Spain",
    city: "Canarias",
    location: "Spain",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-islas-canarias-2026" },
  },
  {
    id: "wrc-2026-05-07-wrc-vodafone-rally-de-portugal-2026",
    title: "WRC Vodafone Rally de Portugal 2026",
    startDate: "2026-05-07",
    country: "Portugal",
    city: "Portugal",
    location: "Portugal",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-vodafone-rally-de-portugal-2026" },
  },
  {
    id: "wrc-2026-05-28-wrc-forum8-rally-japan-2026",
    title: "WRC FORUM8 Rally Japan 2026",
    startDate: "2026-05-28",
    country: "Japan",
    city: "Japan",
    location: "Japan",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-japan-2026" },
  },
  {
    id: "wrc-2026-06-25-wrc-eko-acropolis-rally-greece-2026",
    title: "WRC EKO Acropolis Rally Greece 2026",
    startDate: "2026-06-25",
    country: "Greece",
    city: "Greece",
    location: "Greece",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-eko-acropolis-rally-greece-2026" },
  },
  {
    id: "wrc-2026-07-16-wrc-delfi-rally-estonia-2026",
    title: "WRC Delfi Rally Estonia 2026",
    startDate: "2026-07-16",
    country: "Estonia",
    city: "Estonia",
    location: "Estonia",
    region: "World",
    series: "WRC",
    latviaInvolved: true,
    latvianDrivers: ["sesks"],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-delfi-rally-estonia-2026" },
  },
  {
    id: "wrc-2026-07-30-wrc-secto-rally-finland-2026",
    title: "WRC Secto Rally Finland 2026",
    startDate: "2026-07-30",
    country: "Finland",
    city: "Finland",
    location: "Finland",
    region: "World",
    series: "WRC",
    latviaInvolved: true,
    latvianDrivers: ["sesks"],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-secto-rally-finland-2026" },
  },
  {
    id: "wrc-2026-08-27-wrc-ueno-rally-del-paraguay-2026",
    title: "WRC ueno Rally del Paraguay 2026",
    startDate: "2026-08-27",
    country: "Paraguay",
    city: "Paraguay",
    location: "Paraguay",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-del-paraguay-2026" },
  },
  {
    id: "wrc-2026-09-10-wrc-rally-chile-bio-bio-2026",
    title: "WRC Rally Chile Bio Bío 2026",
    startDate: "2026-09-10",
    country: "Chile",
    city: "Chile",
    location: "Chile",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-chile-bio-bio-2026" },
  },
  {
    id: "wrc-2026-10-01-wrc-rally-italia-sardegna-2026",
    title: "WRC Rally Italia Sardegna 2026",
    startDate: "2026-10-01",
    country: "Italy",
    city: "Sardegna",
    location: "Italy",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-italia-sardegna-2026" },
  },
  {
    id: "wrc-2026-11-11-wrc-rally-saudi-arabia-2026",
    title: "WRC Rally Saudi Arabia 2026",
    startDate: "2026-11-11",
    country: "Saudi Arabia",
    city: "Saudi Arabia",
    location: "Saudi Arabia",
    region: "World",
    series: "WRC",
    latviaInvolved: false,
    latvianDrivers: [],
    description: "Official World Rally Championship round.",
    links: { official: "https://www.wrc.com/en/events/wrc-rally-saudi-arabia-2026" },
  },
];
