import { Driver } from "./types";

export const wrcPeople: Driver[] = [
  {
    id: "wrc-adrien-fourmaux",
    name: "Adrien Fourmaux",
    discipline: "Rally",
    achievements: [
      "Official WRC Rally1 driver for Hyundai in the 2026 season.",
      "Front-running pace on asphalt and mixed-surface rallies.",
    ],
    active: true,
    role: "Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "France",
    series: "WRC",
    bio: "French Rally1 driver competing in Hyundai's world championship programme.",
  },
  {
    id: "wrc-esapekka-lappi",
    name: "Esapekka Lappi",
    discipline: "Rally",
    achievements: [
      "Official WRC Rally1 driver for Hyundai in the 2026 season.",
      "Experienced world-level rally winner with strong gravel speed.",
    ],
    active: true,
    role: "Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Finland",
    series: "WRC",
    bio: "Finnish Rally1 driver bringing proven WRC pace and experience to Hyundai's line-up.",
  },
  {
    id: "wrc-thierry-neuville",
    name: "Thierry Neuville",
    discipline: "Rally",
    achievements: [
      "Official WRC Rally1 driver for Hyundai in the 2026 season.",
      "One of the defining championship contenders of the modern WRC era.",
    ],
    active: true,
    role: "Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Belgium",
    series: "WRC",
    bio: "Belgian WRC star known for title fights, precision on tarmac and full-season championship campaigns.",
  },
  {
    id: "wrc-hayden-paddon",
    name: "Hayden Paddon",
    discipline: "Rally",
    achievements: [
      "Official WRC Rally1 driver for Hyundai in the 2026 season.",
      "International rally winner with deep gravel and rough-condition experience.",
    ],
    active: true,
    role: "Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "New Zealand",
    series: "WRC",
    bio: "New Zealand rally driver returning to top-level WRC competition with Hyundai machinery.",
  },
  {
    id: "wrc-dani-sordo",
    name: "Dani Sordo",
    discipline: "Rally",
    achievements: [
      "Official WRC Rally1 driver for Hyundai in the 2026 season.",
      "Veteran WRC winner with long-standing top-class rally experience.",
    ],
    active: true,
    role: "Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Spain",
    series: "WRC",
    bio: "Spanish WRC veteran valued for consistency, setup feedback and event management.",
  },
  {
    id: "wrc-alexandre-coria",
    name: "Alexandre Coria",
    discipline: "Rally",
    achievements: [
      "Official WRC co-driver for Hyundai in the 2026 season.",
      "World-level co-driver pairing with Adrien Fourmaux.",
    ],
    active: true,
    role: "Co-Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "France",
    series: "WRC",
    bio: "French co-driver working at Rally1 level in the WRC with Adrien Fourmaux.",
  },
  {
    id: "wrc-enni-malkonen",
    name: "Enni Malkonen",
    discipline: "Rally",
    achievements: [
      "Official WRC co-driver for Hyundai in the 2026 season.",
      "Part of Hyundai's Rally1 programme on the world stage.",
    ],
    active: true,
    role: "Co-Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Finland",
    series: "WRC",
    bio: "Finnish co-driver competing in the WRC Rally1 field with Esapekka Lappi.",
  },
  {
    id: "wrc-martijn-wydaeghe",
    name: "Martijn Wydaeghe",
    discipline: "Rally",
    achievements: [
      "Official WRC co-driver for Hyundai in the 2026 season.",
      "Regular part of Hyundai's top-line Rally1 championship campaigns.",
    ],
    active: true,
    role: "Co-Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Belgium",
    series: "WRC",
    bio: "Belgian co-driver competing at the front of the Rally1 field alongside Thierry Neuville.",
  },
  {
    id: "wrc-john-kennard",
    name: "John Kennard",
    discipline: "Rally",
    achievements: [
      "Official WRC co-driver for Hyundai in the 2026 season.",
      "Extensive international rally experience in world competition.",
    ],
    active: true,
    role: "Co-Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "New Zealand",
    series: "WRC",
    bio: "New Zealand co-driver bringing veteran experience to Hyundai's Rally1 operation.",
  },
  {
    id: "wrc-candido-carrera",
    name: "Candido Carrera",
    discipline: "Rally",
    achievements: [
      "Official WRC co-driver for Hyundai in the 2026 season.",
      "Top-class international rally navigator in Rally1 competition.",
    ],
    active: true,
    role: "Co-Driver",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "Spain",
    series: "WRC",
    bio: "Spanish co-driver competing in the WRC Rally1 field with Dani Sordo.",
  },
  {
    id: "wrc-andrew-wheatley",
    name: "Andrew Wheatley",
    discipline: "Rally",
    achievements: [
      "Official team principal of Hyundai Shell Mobis World Rally Team in 2026.",
      "Leads Hyundai's Rally1 operation in the world championship.",
    ],
    active: true,
    role: "Team Principal",
    team: "Hyundai Shell Mobis World Rally Team",
    nationality: "United Kingdom",
    series: "WRC",
    bio: "Team principal responsible for Hyundai's world rally programme and Rally1 operation.",
  },
];
